
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Phasedist.h"

void Phasedist__ctx_type_16_init(Phasedist__ctx_type_16 &_output_){
   Phasedist__ctx_type_16 _ctx;
   _ctx.rate = 0x0 /* 0.000000 */;
   _ctx.phase = 0x0 /* 0.000000 */;
   Phasedist__ctx_type_4_init(_ctx._inst3cb);
   Phasedist__ctx_type_5_init(_ctx._inst11a);
   _output_ = _ctx;
   return ;
}

fix16_t Phasedist_phase(Phasedist__ctx_type_16 &_ctx, fix16_t cv, fix16_t reset){
   if(Phasedist_change(_ctx._inst11a,cv)){
      _ctx.rate = Phasedist_cvToRate_1024(cv);
   }
   if(Phasedist_edge(_ctx._inst3cb,(reset > 0x8000 /* 0.500000 */))){
      _ctx.phase = 0x0 /* 0.000000 */;
   }
   else
   {
      _ctx.phase = (_ctx.phase + _ctx.rate);
   }
   if(_ctx.phase > 0x4000000 /* 1024.000000 */){
      _ctx.phase = (-0x4000000 /* -1024.000000 */ + _ctx.phase);
   }
   return (_ctx.phase >> 10);
}

void Phasedist__ctx_type_17_init(Phasedist__ctx_type_17 &_output_){
   Phasedist__ctx_type_17 _ctx;
   _ctx.pre_phase1 = 0x0 /* 0.000000 */;
   Phasedist__ctx_type_16_init(_ctx._inst364);
   Phasedist__ctx_type_6_init(_ctx._inst2b6);
   Phasedist__ctx_type_16_init(_ctx._inst164);
   _output_ = _ctx;
   return ;
}

fix16_t Phasedist_process(Phasedist__ctx_type_17 &_ctx, fix16_t cv, fix16_t detune){
   fix16_t phase1;
   phase1 = Phasedist_phase(_ctx._inst164,cv,0x0 /* 0.000000 */);
   fix16_t comp;
   comp = (0x10000 /* 1.000000 */ + (- phase1));
   fix16_t reset;
   reset = (_ctx.pre_phase1 + (- phase1));
   _ctx.pre_phase1 = phase1;
   fix16_t phase2;
   phase2 = Phasedist_phase(_ctx._inst364,(cv + Phasedist_smooth(_ctx._inst2b6,(detune >> 1))),reset);
   fix16_t sine;
   sine = Phasedist_nsine(phase2);
   return fix_mul(comp,sine);
}


